// Code generated by "stringer -type=PlayerDecisionKind"; DO NOT EDIT.

package uknow

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlayerDecisionPullFromDeck-1]
	_ = x[PlayerDecisionPullFromPile-2]
	_ = x[PlayerDecisionPlayHandCard-3]
}

const _PlayerDecisionKind_name = "PlayerDecisionPullFromDeckPlayerDecisionPullFromPilePlayerDecisionPlayHandCard"

var _PlayerDecisionKind_index = [...]uint8{0, 26, 52, 78}

func (i PlayerDecisionKind) String() string {
	i -= 1
	if i < 0 || i >= PlayerDecisionKind(len(_PlayerDecisionKind_index)-1) {
		return "PlayerDecisionKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PlayerDecisionKind_name[_PlayerDecisionKind_index[i]:_PlayerDecisionKind_index[i+1]]
}
