// Code generated by "stringer -type=ReplCommandKind"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdNone-0]
	_ = x[CmdAskUserToPlay-1]
	_ = x[CmdDeclareReady-2]
	_ = x[CmdQuit-3]
	_ = x[CmdConnect-4]
	_ = x[CmdTableSummary-5]
	_ = x[CmdDumpDrawDeck-6]
	_ = x[CmdShowHand-7]
	_ = x[CmdDropCard-8]
	_ = x[CmdDrawCard-9]
	_ = x[CmdPass-10]
	_ = x[CmdDrawCardFromPile-11]
	_ = x[CmdSetWildCardColor-12]
	_ = x[CmdNoChallenge-13]
	_ = x[CmdChallenge-14]
}

const _ReplCommandKind_name = "CmdNoneCmdAskUserToPlayCmdDeclareReadyCmdQuitCmdConnectCmdTableSummaryCmdDumpDrawDeckCmdShowHandCmdDropCardCmdDrawCardCmdPassCmdDrawCardFromPileCmdSetWildCardColorCmdNoChallengeCmdChallenge"

var _ReplCommandKind_index = [...]uint8{0, 7, 23, 38, 45, 55, 70, 85, 96, 107, 118, 125, 144, 163, 177, 189}

func (i ReplCommandKind) String() string {
	if i < 0 || i >= ReplCommandKind(len(_ReplCommandKind_index)-1) {
		return "ReplCommandKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReplCommandKind_name[_ReplCommandKind_index[i]:_ReplCommandKind_index[i+1]]
}
