// Code generated by "stringer -type=UIAction"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[uiUpdated-0]
	_ = x[uiRedrawGrid-1]
	_ = x[uiClearRedrawGrid-2]
	_ = x[uiStop-3]
}

const _UIAction_name = "uiUpdateduiRedrawGriduiClearRedrawGriduiStop"

var _UIAction_index = [...]uint8{0, 9, 21, 38, 44}

func (i UIAction) String() string {
	if i < 0 || i >= UIAction(len(_UIAction_index)-1) {
		return "UIAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UIAction_name[_UIAction_index[i]:_UIAction_index[i+1]]
}
